### ISSUE TITLE
Installation: conda_env.sh is missing

### ISSUE THREAD

**Issue by ckeeling** [jlanga/smsk_tuxedo2#3]
Hello @jlanga, I am trying to install your project as a means of learning Snakemake for RNAseq, but I'm having a problem setting up the environment.  Step 1 on installation, ```bash src/install/conda_env.sh```.  This file is missing from this directory.

**Comment by jlanga** [comment]
Hi @ckeeling, I totally forgot to update the readme file.

You don't need to run that script. Just make sure snakemake is fairly recent and type `snakemake --use-conda -j 32` and it will install everything it needs to run.

**Comment by jlanga** [comment]
#4  should fix this

**Comment by ckeeling** [comment]
Thanks @jlanga I found the following subsequent difficulties:
Step2 : ```snakemake --create-envs-only``` -> ```snakemake --use-conda --create-envs-only```

Then, when I run it I get:

```
CreateCondaEnvironmentException:
Could not create conda environment from /lustre04/scratch/ckeeling/snakemake/smsk_tuxedo2/src/snakefiles/de.yml:
Collecting package metadata: ...working... done
Solving environment: ...working... failed
WARNING: The conda.compat module is deprecated and will be removed in a future release.

ResolvePackageNotFound: 
  - r-dplyr==0.4.3=r3.2.2_0a -> r-base=3.2.2
  - r-devtools==1.9.1=r3.2.2_0a -> r-base=3.2.2
  - bioconductor-genefilter==1.52.1=r3.2.2_0 -> r=3.2.2
```

Also, I think RSkittleBrewer isn't a package in BioConductor (used in line 11 of de.py), but is downloaded from GitHub: [https://github.com/alyssafrazee/RSkittleBrewer](url) with ```devtools::install_github('alyssafrazee/RSkittleBrewer')```.

**Comment by jlanga** [comment]
Humm. I ran it yesterday from scratch, cloning, installing and executing, and worked well.

About RSkittleBrewer, when specifying the user/repo name of the package, it understands it is something from github, equivalent to devtools::install_github.

**Comment by jlanga** [comment]
Hi @ckeeling . Does it work?

**Comment by ckeeling** [comment]
Hi @jlanga,

Yes, it now works with your test data, but I had to replace:
lines 12-14 of de.py with:
```
       Rscript \
        -e 'devtools::install_github("alyssafrazee/RSkittleBrewer")' \
        2> {log} 1>&2
```

And, I removed the version specifications of the dependencies for all the yml files.  Some of the dependencies were failing to install otherwise, including devtools.
